/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Jan 24 15:19:20 2018. */

#include "DigitalKey.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ingeek_DK_Time_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ingeek_DK_Time, seconds, seconds, 0),
    PB_LAST_FIELD
};

const pb_field_t ingeek_EncryptedData_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ingeek_EncryptedData, etype, etype, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, ingeek_EncryptedData, kvno, etype, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, STATIC  , OTHER, ingeek_EncryptedData, cipher, kvno, 0),
    PB_LAST_FIELD
};

const pb_field_t ingeek_DK_AuthX_fields[11] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ingeek_DK_AuthX, flags, flags, 0),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, ingeek_DK_AuthX, keys, flags, &ingeek_EncryptedData_fields),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, ingeek_DK_AuthX, crealm, keys, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, ingeek_DK_AuthX, cname, crealm, 0),
    PB_FIELD(  5, MESSAGE , REQUIRED, STATIC  , OTHER, ingeek_DK_AuthX, authtime, cname, &ingeek_DK_Time_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, ingeek_DK_AuthX, starttime, authtime, &ingeek_DK_Time_fields),
    PB_FIELD(  7, MESSAGE , REQUIRED, STATIC  , OTHER, ingeek_DK_AuthX, endtime, starttime, &ingeek_DK_Time_fields),
    PB_FIELD(  8, MESSAGE , OPTIONAL, STATIC  , OTHER, ingeek_DK_AuthX, renew_till, endtime, &ingeek_DK_Time_fields),
    PB_FIELD(  9, BYTES   , OPTIONAL, STATIC  , OTHER, ingeek_DK_AuthX, caddr, renew_till, 0),
    PB_FIELD( 10, INT32   , REQUIRED, STATIC  , OTHER, ingeek_DK_AuthX, auth_data, caddr, 0),
    PB_LAST_FIELD
};

const pb_field_t ingeek_DK_AuthG_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ingeek_DK_AuthG, flags, flags, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, ingeek_DK_AuthG, df, flags, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, STATIC  , OTHER, ingeek_DK_AuthG, s_cmac, df, 0),
    PB_LAST_FIELD
};

const pb_field_t ingeek_DK_SessionX_fields[9] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ingeek_DK_SessionX, avno, avno, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, ingeek_DK_SessionX, crealm, avno, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, ingeek_DK_SessionX, cname, crealm, 0),
    PB_FIELD(  4, MESSAGE , REQUIRED, STATIC  , OTHER, ingeek_DK_SessionX, ctime, cname, &ingeek_DK_Time_fields),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, ingeek_DK_SessionX, cusec, ctime, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, ingeek_DK_SessionX, EncryptionKey, cusec, 0),
    PB_FIELD(  7, BYTES   , REQUIRED, STATIC  , OTHER, ingeek_DK_SessionX, seq_number, EncryptionKey, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, ingeek_DK_SessionX, auth_data, seq_number, 0),
    PB_LAST_FIELD
};

const pb_field_t ingeek_DK_SessionG_fields[10] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ingeek_DK_SessionG, avno, avno, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, ingeek_DK_SessionG, TRnd, avno, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, STATIC  , OTHER, ingeek_DK_SessionG, SEID, TRnd, 0),
    PB_FIELD(  4, BYTES   , REQUIRED, STATIC  , OTHER, ingeek_DK_SessionG, CRnD, SEID, 0),
    PB_FIELD(  5, BYTES   , REQUIRED, STATIC  , OTHER, ingeek_DK_SessionG, TEEID, CRnD, 0),
    PB_FIELD(  6, BYTES   , OPTIONAL, STATIC  , OTHER, ingeek_DK_SessionG, KICC, TEEID, 0),
    PB_FIELD(  7, BYTES   , OPTIONAL, STATIC  , OTHER, ingeek_DK_SessionG, KIFD, KICC, 0),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, ingeek_DK_SessionG, KPRE, KIFD, 0),
    PB_FIELD(  9, MESSAGE , OPTIONAL, STATIC  , OTHER, ingeek_DK_SessionG, ENDTIME, KPRE, &ingeek_DK_Time_fields),
    PB_LAST_FIELD
};

const pb_field_t ingeek_DK_Cmd_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ingeek_DK_Cmd, command, command, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ingeek_DK_Cmd, result, command, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, ingeek_DK_Cmd, index, result, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, ingeek_DK_Cmd, permission, index, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, STATIC  , OTHER, ingeek_DK_Cmd, sparam, permission, 0),
    PB_LAST_FIELD
};

const pb_field_t ingeek_DK_InfoW_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ingeek_DK_InfoW, etype, etype, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, ingeek_DK_InfoW, VIN, etype, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, STATIC  , OTHER, ingeek_DK_InfoW, KEY, VIN, 0),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, ingeek_DK_InfoW, sign, KEY, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, ingeek_DK_InfoW, index, sign, 0),
    PB_LAST_FIELD
};

const pb_field_t ingeek_DK_InfoR_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, ingeek_DK_InfoR, VIN, VIN, 0),
    PB_FIELD(  2, BYTES   , REQUIRED, STATIC  , OTHER, ingeek_DK_InfoR, TRnd, VIN, 0),
    PB_LAST_FIELD
};

const pb_field_t ingeek_DK_Msg_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ingeek_DK_Msg, message, message, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, ingeek_DK_Msg, result, message, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, ingeek_DK_Msg, index, result, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, ingeek_DK_Msg, permission, index, 0),
    PB_FIELD(  5, BYTES   , OPTIONAL, STATIC  , OTHER, ingeek_DK_Msg, sparam, permission, 0),
    PB_LAST_FIELD
};

const pb_field_t ingeek_DK_RTC_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ingeek_DK_RTC, etype, etype, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, ingeek_DK_RTC, VIN, etype, 0),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, ingeek_DK_RTC, rtc_time, VIN, &ingeek_DK_Time_fields),
    PB_FIELD(  4, BYTES   , OPTIONAL, STATIC  , OTHER, ingeek_DK_RTC, sign, rtc_time, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ingeek_DK_AuthX, keys) < 65536 && pb_membersize(ingeek_DK_AuthX, authtime) < 65536 && pb_membersize(ingeek_DK_AuthX, starttime) < 65536 && pb_membersize(ingeek_DK_AuthX, endtime) < 65536 && pb_membersize(ingeek_DK_AuthX, renew_till) < 65536 && pb_membersize(ingeek_DK_SessionX, ctime) < 65536 && pb_membersize(ingeek_DK_SessionG, ENDTIME) < 65536 && pb_membersize(ingeek_DK_RTC, rtc_time) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ingeek_DK_Time_ingeek_EncryptedData_ingeek_DK_AuthX_ingeek_DK_AuthG_ingeek_DK_SessionX_ingeek_DK_SessionG_ingeek_DK_Cmd_ingeek_DK_InfoW_ingeek_DK_InfoR_ingeek_DK_Msg_ingeek_DK_RTC)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ingeek_DK_AuthX, keys) < 256 && pb_membersize(ingeek_DK_AuthX, authtime) < 256 && pb_membersize(ingeek_DK_AuthX, starttime) < 256 && pb_membersize(ingeek_DK_AuthX, endtime) < 256 && pb_membersize(ingeek_DK_AuthX, renew_till) < 256 && pb_membersize(ingeek_DK_SessionX, ctime) < 256 && pb_membersize(ingeek_DK_SessionG, ENDTIME) < 256 && pb_membersize(ingeek_DK_RTC, rtc_time) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ingeek_DK_Time_ingeek_EncryptedData_ingeek_DK_AuthX_ingeek_DK_AuthG_ingeek_DK_SessionX_ingeek_DK_SessionG_ingeek_DK_Cmd_ingeek_DK_InfoW_ingeek_DK_InfoR_ingeek_DK_Msg_ingeek_DK_RTC)
#endif


/* @@protoc_insertion_point(eof) */
