#ifndef INGEEK_CONFIG_H
#define INGEEK_CONFIG_H

#define INGEEK_SMALL_CIPHER_C    //2640上开启这个宏，RH850上关闭这个宏
#include "util_int.h"
//#define INGEEK_UNUSED_FUN
//#define INGEEK_AES_ROM_TABLES
#define INGEEK_CIPHER_MODE_CBC
#define INGEEK_CIPHER_PADDING_PKCS7
//#define INGEEK_CIPHER_PADDING_ONE_AND_ZEROS
//#define INGEEK_CIPHER_PADDING_ZEROS_AND_LEN
//#define INGEEK_CIPHER_PADDING_ZEROS
#define INGEEK_ECP_DP_SECP256R1_ENABLED
//#define INGEEK_ECP_DP_SECP256K1_ENABLED
//#define INGEEK_ECP_DP_BP256R1_ENABLED
#define INGEEK_SHA256_SMALLER
#define INGEEK_AES_C
#define INGEEK_ASN1_PARSE_C
#define INGEEK_ASN1_WRITE_C
#define INGEEK_BIGNUM_C
//#define INGEEK_CMAC_C
#define INGEEK_ECDH_C
#define INGEEK_ECDSA_C
#define INGEEK_ECP_C
#define INGEEK_MD_C
#define INGEEK_SHA256_C

#endif /* INGEEK_CONFIG_H */
